config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :conversations, only: [:index, :show, :destroy] do
      member do
        post :restore
        post :reply
        post :mark_as_read
      end
      collection do
        delete :empty_trash
      end
  end

  resources :messages, only: [:new, :create]

  resources :users, only: [:index ] do
    member do
      post :assign_as_admin
      post :unassign_as_admin
    end
  end

  resources :services, only: [:index]

  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   acts_as_messageable

   # blogs

   scope :admin, -> { where(admin: true) }

   def self.assign_as_admin(user_id)
   		toggle_admin_status(user_id, true)
   end

   def self.unassign_as_admin(user_id)
   		toggle_admin_status(user_id, false)
   end

   def mailboxer_email(object)
   		email
   end

    def admin?
      admin
    end

   private
   def self.toggle_admin_status(user_id, status)
   		user  = get_obj(user_id)
   		user.update_attribute :admin, status
   end

   def self.get_obj user_id
   		User.find(user_id)
   end
end

app/models/wordpress.rb
class Wordpress

	include HTTParty

	base_uri Constants.wordpress_base_uri

	def initialize
		@options = { query: {context: 'display', number: Constants.posts_count} }
	end

	def posts
		posts_url = Constants.wordpress_rest_uri + '/sites/' + Constants.wordpress_blog_site_id + "/posts"
		puts posts_url
		self.class.get(posts_url, @options)

		# posts = self.class.get('/rest/v1.1/sites/81038511/posts/', @options)
		# puts " ********** MODEL *******"
		# puts posts

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound do
    flash[:warning] = 'Resource not found.'
    redirect_back_or root_path
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def redirect_back_or(path)
    redirect_to request.referer || path
  end

  def authenticate_blogger
    current_user.admin?
  end

  def blogit_admin_sign_out_url
    destroy_user_session_path
  end

  def current_blogger
    current_user
  end


  # def blog
  #   redirect_to "https://nrtechbytes.wordpress.com", :status => :moved_permanently
  #   # redirect_to "https://nrtechbytes.wordpress.com#{request.fullpath.gsub('/blog','')}", :status => :moved_permanently
  # end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
	before_action :get_mailbox
	before_action :get_box, only: [:index]
	before_action :get_conversation, except: [:index, :empty_trash]

	def show
	end

	def index
		if @box.eql? "inbox"
			@conversations = @mailbox.inbox
		elsif @box.eql? "sent"
			@conversations = @mailbox.sentbox
		else
			@conversations = @mailbox.trash
		end

		@conversations = @conversations.paginate(page: params[:page], per_page: 10)
		# render @conversations.inspect
		# render json: @conversations.as_json, status: :ok
	end

	def reply 
		current_user.reply_to_conversation(@conversation, params[:body])
		flash[:success] = 'Reply Sent'
		redirect_to conversation_path(@conversation)
	end

	def destroy
	  @conversation.move_to_trash(current_user)
	  flash[:success] = 'The conversation was moved to trash.'
	  redirect_to conversations_path
	end

	def restore
	  @conversation.untrash(current_user)
	  flash[:success] = 'The conversation was restored.'
	  redirect_to conversations_path
	end

	def empty_trash
	  @mailbox.trash.each do |conversation|
	    conversation.receipts_for(current_user).update_all(deleted: true)
	  end
	  flash[:success] = 'Your trash was cleaned!'
	  redirect_to conversations_path
	end

	def mark_as_read
		@conversation.mark_as_read(current_user)
		flash[:success] = 'The conversation was marked as read.'
		redirect_to conversations_path
	end

	private

	def get_mailbox
		@mailbox ||= current_user.mailbox
	end

	def get_conversation
		@conversation ||= @mailbox.conversations.find(params[:id])
	end

	def get_box
		if params[:box].blank? or !["inbox", "sent", "trash"].include?(params[:box])
			params[:box] = 'inbox'
		end
		@box = params[:box]
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		wordpress = Wordpress.new
		@posts = wordpress.posts
		@site_domain = request.host_with_port
	end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!

	def new
	end

	def create
		recipients = User.where(id: params['recipients'])
		conversation = current_user.send_message(recipients, params[:message][:body], params[:message][:subject]).conversation
		flash[:success] = "Message has been sent!"
		redirect_to conversation_path(conversation)
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :authenticate_admin!

	def index
		@users = User.order('created_at DESC').paginate(page: params[:page], per_page: 30)
	end

	def assign_as_admin
		User.assign_as_admin(params[:id])
		flash[:success] =  "Successfully assigned user as admin"
		redirect_to users_path
	end

	def unassign_as_admin
		User.unassign_as_admin(params[:id])
		flash[:success] =  "Successfully un-assigned user as admin"
		redirect_to users_path
	end

	private
	def authenticate_admin!
		unless current_user.try(:admin?)
      		flash[:danger] = 'You must be an admin to access this section'
      		redirect_to root_path # halts request cycle
    	end
    end	

end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_header(text)
		content_for(:page_header) {text.to_s}
	end

	def gravatar_for(user, size = 30, title = user.name)
		image_tag gravatar_image_url(user.email, size: size), title: title, class: 'img-rounded'
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
	def mailbox_section(title, current_box, opts = {})
		opts[:class] = opts.fetch(:class, '')
		opts[:class] += ' active' if title.downcase == current_box
		content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
	end
end

app/helpers/messages_helper.rb
module MessagesHelper
	def recipients_options
		
		users = current_user.admin? ?
			User.all : User.admin

		s = ''
		users.each do |user|
			s << "<option value='#{user.id}'>#{user.name}</option>"
		end
		s.html_safe
	end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix">
	<%= link_to conversation.subject, conversation_path(conversation) %>

	<div class="btn-group-vertical pull-right">
		<% if conversation.is_trashed?(current_user) %>
			<%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
		<% else %>
			<%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger', method: :delete,
                  data: {confirm: 'Are you sure?'} %>
            <% if conversation.is_unread?(current_user) %>
            	<%= link_to 'Mark as read', mark_as_read_conversation_path(conversation), class: 'btn btn-xs btn-info', method: :post %>
            <% end %>
		<% end %>
	</div>
	
	<p> <%=  render 'conversations/participants', conversation: conversation %> </p>

	<p>
		<%= conversation.last_message.body  %>
			<small>(<span class="text-muted"><%=  conversation.last_message.created_at.strftime("%-d %B %Y, %H:%M:%S") %> </span>)</small>
		</p>
</li>

app/views/conversations/_participants.html.erb
<% conversation.participants.each do |participant| %>

	<% unless participant == current_user %>
		<%= gravatar_for participant %>
	<% end %>
<% end %>

app/views/conversations/index.html.erb
<% page_header "Your Conversations" %>

<p><%= link_to "Start Conversation", new_message_path, class: 'btn btn-lg btn-primary' %></p>

<div class="row">
	<div class="col-sm-3">
		<ul class="nav nav-pills nav-stacked">
			<%= mailbox_section 'inbox', @box %>
			<%= mailbox_section 'sent', @box %>
			<%= mailbox_section 'trash', @box %>
		</ul>
	</div>
		
	<div class="col-sm-9">

		<% if @box == 'trash' %>
		    <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete,
		                   data: {confirm: 'Are you sure?'} %></p>
		<% end %>

		<ul class="list-group">
			<%= render partial: 'conversations/conversation', collection: @conversations %>
		</ul>
		<%= will_paginate @conversations %>
	</div>	
</div>

app/views/conversations/show.html.erb
<% page_header "Conversation" %>

<p>Chatting With 
<%= render 'conversations/participants', conversation: @conversation %>
	
</p>
<div class="panel panel-default">
	<div class="panel-heading"> <%= @conversation.subject %>

		<% if @conversation.is_unread?(current_user) %>
        	<%= link_to 'Mark as read', mark_as_read_conversation_path(@conversation), class: 'btn btn-xs btn-info', method: :post %>
        <% end %>
        <%=  link_to 'Back', conversations_path, class: 'btn btn-xs btn-primary' %>
	</div>

	<div class="panel-body">
		<div class="messages">
			<% @conversation.receipts_for(current_user).each do |receipt| %>
				<div class="media">
				
					<% message = receipt.message%>
					<div class="media-left">
						<%= gravatar_for message.sender, 45, message.sender.name %>
					</div>
					<div class="media-body">
						<h6 class="media-heading">
							<%= message.created_at.strftime("%-d %B %Y, %H:%M:%S") %>
						</h6>
						<%= message.body %>
					</div>
				</div>
			<% end %>
		</div>
	</div>	

	<%= form_tag reply_conversation_path(@conversation), method: :post do %>
		<div>
			<%= text_area_tag 'body', nil, cols: 3, class: 'form-control', placeholder: 'Type something...', required: true %>
		</div>
		<div class="row">
			<div class="col-md-2">
			<%= submit_tag "Send message", class: 'btn btn-primary' %>
			</div>
			<div class="col-md-4">
				<%=  link_to 'Back', conversations_path, class: 'btn btn-primary' %>
			</div>

		</div>
	<% end %>

</div>

app/views/home/index.html.erb
	<div class="container">
		<div class="jumbotron" style="text-align: center">
			<h1 >Hello World!</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit...</p>
      		<p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris...</p>
			<a class="btn btn-default">Watch Now!</a>
			<a class="btn btn-info">Tweet it!</a>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<% @posts.parsed_response['posts'].each do |post| 
				post_url = URI.parse(post['URL'])  
				blog_url = @site_domain + '/blog' + post_url.path %>
				<div class="col-md-3">
					<div class="row">
						<h3> <%= link_to post['title'].html_safe, blog_url  %>
						</h3>
					</div>
					<div class="row">
						<p><%= post['excerpt'].html_safe %> </p>
					</div>
					<div class="row">
						<%= link_to 'Read More', blog_url, :class => "btn btn-info" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Garima Raj & Associates</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-static-top">
	<div class="container">
		<%= link_to 'Garima Raj & Associates', root_path, class: 'navbar-brand' %>

		<button class="navbar-toggle" data-toggle = "collapse" data-target=".navHeaderCollapse"> 
			<span class = "icon-bar"> </span>
			<span class = "icon-bar"> </span>
			<span class = "icon-bar"> </span>
		</button>

		<div class="collapse navbar-collapse navHeaderCollapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to 'Home', root_path %></li>	
				<li class="dropdown <%= 'active' if current_page?(services_path) %>" >
					<%= link_to 'Our Services <b class="caret"></b>'.html_safe, services_path, :class => "dropdown-toggle", :data => {:toggle => "dropdown"} %>
					<ul class="dropdown-menu">
						<li><%= link_to 'Company Registration', services_path %>	</li>
						<li><%= link_to 'LLP Registration', services_path %></a>	</li>
						<li><%= link_to 'Secretarial Audit', services_path %></a>	</li>
						<li><%= link_to 'Company Law Board Matters', services_path %></a>	</li>
						<li><%= link_to 'Trademark And Copyright', services_path %></a>	</li>
						<li><%= link_to 'Service Tax', services_path %></a>	</li>
						<li><%= link_to 'Corporate Advisory', services_path %></a>	</li>
					</ul>
				</li>	
				<li><%= link_to 'Blog', '/blog' %></li>
				<li class="dropdown <%= 'active' if  ['users', 'messages', 'conversations'].include?(controller_name) %>" >
					<a href="#" class = "dropdown-toggle" data-toggle = "dropdown" >Online Consultation <b class="caret"></b></a>	
					<ul class="dropdown-menu">
						<% if user_signed_in? %>
							<li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
							<li><%= link_to 'Your Conversations', conversations_path %></li>
							<% if current_user.admin? %>
								<li><%= link_to 'Users', users_path %></li>
							<% end %>
							<li><%= link_to 'Log Out ' + "#{current_user.name}", destroy_user_session_path, method: :delete %></li>
						<% else %>
							<li><%= link_to 'Log In', new_user_session_path %></li>
						<% end %>
					</ul>
				</li>	
				<li><a href="#">News</a>	</li>	
				 <li><a href="#">Contact</a>	</li>	
			</ul>
		</div>
	</div>
</div>	
<div class="container">
	<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>">
			<%= value %>
		</div>
	<% end %>

<!-- 	<div class="page-header">
		<h1><%= yield :page_header %></h1>
	</div> -->

	<%= yield %>
</div>

<footer class="footer">
	<div class="container">
		<div class = "row">
			<div class="col-md-10">
				<p class="text-muted strong"> <strong> Contact Email: <a href="mailto:csgarimaraj@gmail.com?subject=CS Enquiry">csgarimaraj@gmail.com</a></strong></p>
			</div>
			<div class="col-md-2">
				<p class="text-muted text-right "><em>Powered by NRTechBytes</em></p>
			</div>
		</div>
	</div>
</footer>

<!-- <footer>
	<div class="navbar navbar-default navbar-fixed-bottom">
		<div class = "container">
			<p class="navbar-text"> Powered by Garima Raj & Associates</p>
			<a class = "navbar-btn btn-danger btn pull-right" href="http://google.com">Click for additional stuff </a>
		</div>
	</div>

 </footer>-->
</body>
</html>

app/views/messages/new.html.erb
<% page_header "Start Conversation" %>
<%= form_tag messages_path, method: :post do %>
	<div class="form-group">
		<div class="row">
			<div class="col-md-8">
				<%= label_tag 'message[subject]', 'Subject' %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<%= text_field_tag 'message[subject]', nil, size: 100, class: 'form-control', required: true %>
			</div>
		</div>
	</div>

	<div class="form-group">
		<div class="row">
			<div class="col-md-8">
			<%= label_tag 'message[body]', 'Message', class: " control-label" %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<%= text_area_tag 'message[body]', nil, rows: 3, cols: 25, class: 'col-md-4 form-control', required: true %>
			</div>
		</div>
	</div>

	<div class="form-group">
		<div class="row">
			<div class="col-md-8">
				<%=  label_tag 'recipients', 'Choose recipients' %>
			</div>
		</div>
		<div class="row">
			<div class="col-md-8">
				<%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control chosen-it' %>
			</div>
		</div>
	</div>

	<%=  submit_tag 'Send', class: 'btn btn-primary' %>
	
<%end%>

app/views/services/index.html.erb
<h3>The firm provides an array of services, including:</h3>
<h4>Corporate Laws & Secretarial Matters</h4>
<ul>
	<li>Certification Services</li>
	<li>Due Diligence Reports</li>
	<li>Secretarial Audits</li>
	<li>Maintenance of Minutes and other Secretarial/Statutory Records</li>
	<li>Convening and conducting meetings of Board of Directors, Sharehulders etc.</li>
	<li>Arranging various approvals from Government Authorities</li>
	<li>Company Incorporation Services</li>
	<li>Change of Name, Registered office & Objects Clause etc.</li>
	<li>Matters pertaining to Oppression & Mismanagement</li>
	<li>Preparation of search reports.</li>
	<li>Advisory services on matters pertaining to Corporate Disputes.</li>
	<li>Partnership firm Registration</li>
	<li>Easy Exist Scheme</li>
</ul>
<h4>Corporate Restructuring</h4>
<ul>
	<li>Merger & Amalgamation
	<li>Demerger</li>
	<li>Acquisition and Buy outs</li>
	<li>Restructuring of Capital</li>
	<li>Dissulution & Winding up of Companies</li>
	<li>Conversion of Company from Private to Public and vice versa</li>
	<li>Corporatization of Business</li>
	<li>Change of Management</li>
	<li>Slump Sale</li>
</ul>
<h4>Legal Services</h4>
Appearance before the Company Law Board for fullowing matters:
<ul>
	<li>Shifting of registered office</li>
	<li>Compounding of offense</li>
	<li>Condonation of delay</li>
	<li>Oppression and Mismanagement petitions</li>
</ul>
<h4>Liaisoning with Government Departments</h4>
We provide liasoning services and arrange various approvals from various Government departments such as:  Director General of Foreign Trade for allotment of Importer-Exporter Code Number and other matters, Obtaining various approvals from RBI, Company Law Board, Department of Company Affairs, Ministries of Industry, Commerce and Finance
<h4>Limited Liability Partnership Firms</h4>
<ul>
	<li>LLP incorporation</li>
	<li>LLP Conversion</li>
	<li>Change in LLP agreements</li>
</ul>
<h4>IPR SERVICES</h4>
<ul>
	<li>Trade Mark Registration</li>
	<li>Copy Right Registration</li>
</ul>
<h4>DVAT REGISTRATION</h4>
<h4>FSSAI</h4>
<h4>FCRA REGISTRATION</h4>
<h4>SERVICE TAX</h4>

app/views/users/index.html.erb
<% page_header "Users"  %>
<%= will_paginate %>

<ul>
	<% @users.each do |user| %>
		<li>
			<strong><%= user.name %></strong>
			<% unless current_user == user %>
				<%= link_to 'Send Message', new_message_path(to: user.id), class: 'btn btn-default btn-sm' %>
			<% end %>

			<% if !user.admin?  %>
				<%= link_to 'Assign Admin Role', assign_as_admin_user_path(user), class: 'btn btn-default btn-sm', method: :post %>
			<% elsif (user.admin? and current_user != user ) %>
				<%= link_to 'Un-assign Admin Role', unassign_as_admin_user_path(user), class: 'btn btn-default btn-sm', method: :post %>
			<% end %>
		</li>	
	<% end %>
</ul>


<%= will_paginate %>